MUSCLE_GROUPS = [
    "Pecho",
    "Espalda",
    "Piernas",
    "Hombros",
    "Brazos",
    "Core",
    "Gluteos",
    "Cuadriceps",
    "Isquiosurales",
    "Gemelos",
    "Aductores",
    "Abductores",
    "Dorsales",
    "Trapecio",
    "Deltoides",
    "Biceps",
    "Triceps",
    "Antebrazos",
    "Lumbar",
    "Oblicuos",
]

EQUIPMENT = [
    "Barra",
    "Mancuernas",
    "Maquina",
    "Polea",
    "Peso corporal",
    "Banco",
    "Multipower",
    "Prensa de piernas",
    "Hack squat",
    "Maquina convergente",
    "Maquina selectorizada",
    "Peck deck",
    "Polea alta",
    "Polea baja",
    "Cruce de poleas",
    "Barra de dominadas",
    "Paralelas",
    "Banco Scott",
    "Banco romano",
    "Maquina de extension de cuadriceps",
    "Maquina de curl femoral",
    "Maquina de abductores",
    "Maquina de aductores",
    "Maquina de gemelos",
    "Maquina de gluteos",
    "Landmine",
    "Kettlebell",
    "Banda elastica",
    "TRX",
    "Balon medicinal",
    "Caja pliometrica",
    "Disco",
]


def exercise(
    name: str,
    description: str,
    difficulty: str,
    technique_notes: str,
    muscle_groups: list[str],
    equipment: list[str],
    legacy_names: list[str] | None = None,
) -> dict[str, object]:
    data: dict[str, object] = {
        "name": name,
        "description": description,
        "difficulty": difficulty,
        "technique_notes": technique_notes,
        "muscle_groups": muscle_groups,
        "equipment": equipment,
    }
    if legacy_names:
        data["legacy_names"] = legacy_names
    return data


EXERCISES = [
    # Pecho
    exercise("Press banca con barra", "Empuje horizontal pesado para pecho, hombro anterior y triceps.", "intermediate", "Retrae escapulas, apoya los pies y controla el descenso hasta el pecho.", ["Pecho", "Hombros", "Triceps"], ["Barra", "Banco"], ["Press banca"]),
    exercise("Press banca con mancuernas", "Variante de press horizontal con mayor recorrido y trabajo estabilizador.", "intermediate", "Mantiene las munecas neutras y baja las mancuernas de forma simetrica.", ["Pecho", "Hombros", "Triceps"], ["Mancuernas", "Banco"]),
    exercise("Press banca en multipower", "Press horizontal guiado para trabajar pecho con trayectoria estable.", "beginner", "Ajusta el banco para que la barra baje sobre la parte media del pecho.", ["Pecho", "Hombros", "Triceps"], ["Multipower", "Banco"]),
    exercise("Press banca agarre cerrado", "Press horizontal con enfasis en triceps y pecho interno.", "intermediate", "Usa un agarre algo mas cerrado que hombros sin forzar las munecas.", ["Pecho", "Triceps", "Hombros"], ["Barra", "Banco"]),
    exercise("Press banca con pausa", "Press banca con parada controlada en el pecho para mejorar fuerza y tecnica.", "advanced", "Mantiene tension durante la pausa sin rebotar la barra.", ["Pecho", "Hombros", "Triceps"], ["Barra", "Banco"]),
    exercise("Press inclinado con barra", "Empuje inclinado para enfatizar la zona superior del pecho.", "intermediate", "Mantiene el banco entre 25 y 45 grados y evita arquear en exceso.", ["Pecho", "Hombros", "Triceps"], ["Barra", "Banco"]),
    exercise("Press inclinado con mancuernas", "Press inclinado unilateral libre para pecho superior y estabilizacion.", "intermediate", "Baja con control y junta las mancuernas sin golpearlas arriba.", ["Pecho", "Hombros", "Triceps"], ["Mancuernas", "Banco"]),
    exercise("Press inclinado en multipower", "Press inclinado guiado para pecho superior.", "beginner", "Coloca el banco centrado y evita que los codos se abran demasiado.", ["Pecho", "Hombros", "Triceps"], ["Multipower", "Banco"]),
    exercise("Press declinado con barra", "Empuje declinado para pecho con menor demanda del hombro anterior.", "intermediate", "Asegura los pies y controla la barra hacia la zona baja del pecho.", ["Pecho", "Triceps", "Hombros"], ["Barra", "Banco"]),
    exercise("Press declinado con mancuernas", "Variante declinada con mancuernas para pecho y triceps.", "intermediate", "Mantiene el recorrido controlado y evita perder posicion en el banco.", ["Pecho", "Triceps", "Hombros"], ["Mancuernas", "Banco"]),
    exercise("Press pecho en maquina", "Empuje horizontal en maquina para trabajar pecho con soporte estable.", "beginner", "Ajusta el asiento para que las asas queden a la altura media del pecho.", ["Pecho", "Hombros", "Triceps"], ["Maquina selectorizada"]),
    exercise("Press pecho en maquina convergente", "Empuje horizontal convergente con recorrido guiado.", "beginner", "Empuja sin despegar la espalda y evita bloquear agresivamente los codos.", ["Pecho", "Hombros", "Triceps"], ["Maquina convergente"]),
    exercise("Press inclinado en maquina", "Empuje inclinado en maquina para pecho superior.", "beginner", "Ajusta el asiento para empujar en una linea ligeramente ascendente.", ["Pecho", "Hombros", "Triceps"], ["Maquina convergente"]),
    exercise("Press declinado en maquina", "Empuje guiado con enfasis en pecho inferior.", "beginner", "Mantiene escapulas apoyadas y evita elevar los hombros.", ["Pecho", "Triceps"], ["Maquina convergente"]),
    exercise("Aperturas con mancuernas", "Aislamiento de pecho con recorrido amplio en banco plano.", "intermediate", "Flexiona ligeramente los codos y no bajes mas alla de tu movilidad.", ["Pecho", "Hombros"], ["Mancuernas", "Banco"]),
    exercise("Aperturas inclinadas con mancuernas", "Aislamiento de pecho superior en banco inclinado.", "intermediate", "Controla la apertura y mantiene tension en el pecho durante todo el recorrido.", ["Pecho", "Hombros"], ["Mancuernas", "Banco"]),
    exercise("Aperturas declinadas con mancuernas", "Aislamiento de pecho en banco declinado.", "intermediate", "Evita convertirlo en press y conserva una ligera flexion de codo.", ["Pecho"], ["Mancuernas", "Banco"]),
    exercise("Aperturas en polea", "Aislamiento de pecho con tension constante en poleas.", "beginner", "Cruza las manos solo si mantienes control escapular y tension en el pecho.", ["Pecho", "Hombros"], ["Cruce de poleas"]),
    exercise("Aperturas en polea alta", "Cruce desde polea alta para enfatizar fibras inferiores del pecho.", "beginner", "Inclina ligeramente el torso y junta las manos delante de la cadera.", ["Pecho"], ["Cruce de poleas", "Polea alta"]),
    exercise("Aperturas en polea baja", "Cruce desde polea baja para enfatizar pecho superior.", "intermediate", "Eleva las manos en diagonal sin encoger los hombros.", ["Pecho", "Hombros"], ["Cruce de poleas", "Polea baja"]),
    exercise("Aperturas en peck deck", "Aislamiento de pecho en maquina peck deck.", "beginner", "Ajusta el asiento y junta los brazos sin despegar la espalda.", ["Pecho"], ["Peck deck"]),
    exercise("Pullover con mancuerna", "Movimiento de extension de hombro para pecho y dorsales.", "intermediate", "Mantiene costillas controladas y no fuerces el hombro al bajar.", ["Pecho", "Dorsales", "Core"], ["Mancuernas", "Banco"]),
    exercise("Pullover en polea alta", "Extension de hombro en polea con tension continua.", "beginner", "Mantiene brazos casi estirados y lleva la barra hacia los muslos.", ["Pecho", "Dorsales"], ["Polea alta"]),
    exercise("Fondos para pecho", "Empuje en paralelas con inclinacion del torso para pecho y triceps.", "intermediate", "Inclina el torso y baja solo hasta rango controlado de hombro.", ["Pecho", "Triceps", "Hombros"], ["Paralelas", "Peso corporal"]),
    exercise("Flexiones", "Empuje horizontal con peso corporal.", "beginner", "Mantiene el cuerpo alineado y baja el pecho entre las manos.", ["Pecho", "Hombros", "Triceps", "Core"], ["Peso corporal"]),
    exercise("Flexiones inclinadas", "Flexion con manos elevadas para reducir dificultad.", "beginner", "Mantiene linea corporal y controla la bajada.", ["Pecho", "Hombros", "Triceps", "Core"], ["Peso corporal", "Banco"]),
    exercise("Flexiones declinadas", "Flexion con pies elevados para aumentar demanda del pecho superior.", "intermediate", "No hundas la cadera y controla la posicion del hombro.", ["Pecho", "Hombros", "Triceps", "Core"], ["Peso corporal", "Banco"]),
    exercise("Flexiones diamante", "Flexion cerrada con enfasis en triceps y pecho interno.", "intermediate", "Coloca manos cerca sin dolor en munecas y mantiene codos controlados.", ["Pecho", "Triceps", "Core"], ["Peso corporal"]),
    exercise("Flexiones con banda", "Flexion con resistencia elastica para aumentar dificultad.", "intermediate", "Coloca la banda firme sobre la espalda y bloquea el core.", ["Pecho", "Hombros", "Triceps", "Core"], ["Peso corporal", "Banda elastica"]),
    exercise("Press con banda elastica", "Empuje horizontal con banda para pecho y triceps.", "beginner", "Ancla la banda a la altura del pecho y empuja con recorrido estable.", ["Pecho", "Triceps"], ["Banda elastica"]),
    exercise("Press en suelo con barra", "Press horizontal desde el suelo con recorrido limitado.", "intermediate", "Pausa los triceps en el suelo sin relajar la espalda alta.", ["Pecho", "Triceps", "Hombros"], ["Barra"]),
    exercise("Press en suelo con mancuernas", "Press desde el suelo con mancuernas, util para limitar rango de hombro.", "beginner", "Baja hasta apoyar suavemente los triceps y empuja en vertical.", ["Pecho", "Triceps", "Hombros"], ["Mancuernas"]),

    # Espalda
    exercise("Dominadas", "Traccion vertical con peso corporal para dorsales y brazos.", "intermediate", "Inicia con depresion escapular y evita balanceos excesivos.", ["Espalda", "Dorsales", "Biceps", "Core"], ["Barra de dominadas", "Peso corporal"], ["Dominadas"]),
    exercise("Dominadas supinas", "Dominada con agarre supino y mayor participacion del biceps.", "intermediate", "Lleva el pecho hacia la barra manteniendo hombros lejos de las orejas.", ["Espalda", "Dorsales", "Biceps"], ["Barra de dominadas", "Peso corporal"]),
    exercise("Dominadas neutras", "Dominada con agarre neutro, comoda para hombros y codos.", "intermediate", "Sube sin balanceo y controla la extension completa abajo.", ["Espalda", "Dorsales", "Biceps"], ["Barra de dominadas", "Peso corporal"]),
    exercise("Dominadas asistidas en maquina", "Traccion vertical asistida para progresar hacia dominadas libres.", "beginner", "Usa una asistencia que permita rango completo y controlado.", ["Espalda", "Dorsales", "Biceps"], ["Maquina selectorizada"]),
    exercise("Dominadas con banda", "Dominada asistida con banda elastica.", "beginner", "Mantiene tension constante y no rebotes en la banda.", ["Espalda", "Dorsales", "Biceps"], ["Barra de dominadas", "Banda elastica"]),
    exercise("Dominadas lastradas", "Dominada con carga adicional para fuerza avanzada.", "advanced", "Usa lastre controlado y evita recortar el recorrido.", ["Espalda", "Dorsales", "Biceps", "Core"], ["Barra de dominadas", "Peso corporal", "Disco"]),
    exercise("Jalon al pecho", "Traccion vertical en polea para dorsales.", "beginner", "Lleva la barra al pecho alto sin tirar con el cuello ni balancearte.", ["Espalda", "Dorsales", "Biceps"], ["Polea alta"]),
    exercise("Jalon al pecho agarre estrecho", "Jalon con agarre cerrado para dorsales y flexores de codo.", "beginner", "Mantiene torso estable y codos hacia abajo.", ["Espalda", "Dorsales", "Biceps"], ["Polea alta"]),
    exercise("Jalon al pecho agarre supino", "Jalon supino con mayor enfasis en biceps.", "beginner", "No hiperextiendas la espalda al tirar y controla el retorno.", ["Espalda", "Dorsales", "Biceps"], ["Polea alta"]),
    exercise("Jalon tras nuca", "Variante de jalon hacia la nuca con alta demanda de movilidad.", "advanced", "Usalo solo si no genera molestias y mantienes control cervical.", ["Espalda", "Dorsales", "Hombros"], ["Polea alta"]),
    exercise("Jalon unilateral en polea", "Traccion vertical a un brazo para dorsales.", "beginner", "Tira con el codo hacia la cadera y evita rotar el torso.", ["Espalda", "Dorsales", "Biceps"], ["Polea alta"]),
    exercise("Pullover en polea", "Extension de hombro en polea para dorsales.", "beginner", "Mantiene brazos casi estirados y costillas controladas.", ["Espalda", "Dorsales", "Core"], ["Polea alta"]),
    exercise("Remo con barra", "Traccion horizontal con barra para espalda y brazos.", "intermediate", "Mantener bisagra estable y llevar la barra hacia el torso.", ["Espalda", "Dorsales", "Biceps", "Lumbar"], ["Barra"], ["Remo con barra"]),
    exercise("Remo Pendlay", "Remo con barra desde el suelo en cada repeticion.", "advanced", "Mantiene espalda neutra y evita elevar el torso durante el tiron.", ["Espalda", "Dorsales", "Trapecio", "Biceps", "Lumbar"], ["Barra"]),
    exercise("Remo con barra T", "Remo pesado con barra anclada para espalda media.", "intermediate", "Mantiene pecho estable y tira con codos hacia atras.", ["Espalda", "Dorsales", "Trapecio", "Biceps"], ["Landmine", "Barra"]),
    exercise("Remo landmine unilateral", "Remo a un brazo con landmine para dorsales y espalda media.", "intermediate", "Controla la rotacion y lleva el codo hacia la cadera.", ["Espalda", "Dorsales", "Biceps", "Core"], ["Landmine", "Barra"]),
    exercise("Remo con mancuerna", "Remo unilateral apoyado para dorsales.", "beginner", "Apoya rodilla y mano, y tira con el codo hacia la cadera.", ["Espalda", "Dorsales", "Biceps"], ["Mancuernas", "Banco"]),
    exercise("Remo con mancuernas inclinado", "Remo bilateral con mancuernas desde bisagra de cadera.", "intermediate", "Mantiene torso fijo y evita impulsarte con la espalda baja.", ["Espalda", "Dorsales", "Trapecio", "Biceps", "Lumbar"], ["Mancuernas"]),
    exercise("Remo pecho apoyado con mancuernas", "Remo en banco inclinado con soporte para reducir carga lumbar.", "beginner", "Apoya el pecho y tira con codos hacia atras sin encoger hombros.", ["Espalda", "Dorsales", "Trapecio", "Biceps"], ["Mancuernas", "Banco"]),
    exercise("Remo en polea baja", "Traccion horizontal sentada en polea.", "beginner", "Mantiene torso estable y lleva los codos atras sin balancearte.", ["Espalda", "Dorsales", "Biceps"], ["Polea baja"]),
    exercise("Remo en polea baja agarre amplio", "Remo sentado con agarre amplio para espalda alta.", "beginner", "Lleva la barra hacia el pecho y junta escapulas.", ["Espalda", "Trapecio", "Deltoides", "Biceps"], ["Polea baja"]),
    exercise("Remo unilateral en polea", "Remo a un brazo en polea baja.", "beginner", "Evita rotar el tronco y controla el retorno del cable.", ["Espalda", "Dorsales", "Biceps", "Core"], ["Polea baja"]),
    exercise("Remo en maquina", "Traccion horizontal en maquina selectorizada.", "beginner", "Ajusta el pecho al soporte y no eleves los hombros.", ["Espalda", "Dorsales", "Biceps"], ["Maquina selectorizada"]),
    exercise("Remo en maquina convergente", "Remo guiado convergente para espalda media y dorsales.", "beginner", "Tira con codos y conserva el pecho apoyado.", ["Espalda", "Dorsales", "Trapecio", "Biceps"], ["Maquina convergente"]),
    exercise("Remo alto en maquina", "Traccion en maquina con trayectoria alta para espalda superior.", "beginner", "Lleva codos atras y abajo sin elevar el cuello.", ["Espalda", "Trapecio", "Deltoides", "Biceps"], ["Maquina selectorizada"]),
    exercise("Remo invertido", "Traccion horizontal con peso corporal.", "beginner", "Mantiene el cuerpo recto y acerca el pecho a la barra.", ["Espalda", "Dorsales", "Biceps", "Core"], ["Peso corporal", "Multipower"]),
    exercise("Remo invertido en TRX", "Remo con suspension ajustable para espalda.", "beginner", "Ajusta la inclinacion para controlar la dificultad.", ["Espalda", "Dorsales", "Biceps", "Core"], ["TRX", "Peso corporal"]),
    exercise("Face pull", "Tiron a la cara en polea para deltoides posterior y rotadores externos.", "beginner", "Tira hacia la cara con codos altos y control escapular.", ["Hombros", "Deltoides", "Trapecio", "Espalda"], ["Polea alta"]),
    exercise("Pajaros en peck deck", "Aislamiento de deltoides posterior en maquina.", "beginner", "Ajusta las asas y abre sin encoger los hombros.", ["Hombros", "Deltoides", "Trapecio", "Espalda"], ["Peck deck"]),
    exercise("Pajaros con mancuernas", "Apertura inclinada para deltoides posterior y espalda alta.", "beginner", "Mantiene ligera flexion de codo y evita balanceo.", ["Hombros", "Deltoides", "Trapecio", "Espalda"], ["Mancuernas"]),
    exercise("Pajaros en banco inclinado", "Deltoides posterior con pecho apoyado en banco.", "beginner", "Apoya el pecho y abre las mancuernas con control.", ["Hombros", "Deltoides", "Trapecio"], ["Mancuernas", "Banco"]),
    exercise("Encogimientos con barra", "Trabajo directo de trapecio superior.", "beginner", "Eleva hombros en vertical sin girarlos hacia delante.", ["Trapecio", "Espalda"], ["Barra"]),
    exercise("Encogimientos con mancuernas", "Encogimiento bilateral para trapecio.", "beginner", "Mantiene brazos extendidos y pausa arriba.", ["Trapecio", "Espalda"], ["Mancuernas"]),
    exercise("Peso muerto", "Bisagra de cadera para cadena posterior y fuerza general.", "advanced", "Columna neutra, barra cerca del cuerpo y empuje fuerte del suelo.", ["Espalda", "Lumbar", "Piernas", "Gluteos", "Core"], ["Barra"], ["Peso muerto"]),
    exercise("Peso muerto sumo", "Peso muerto con posicion amplia y mayor participacion de aductores.", "advanced", "Abre rodillas, mantiene la barra cerca y empuja el suelo.", ["Gluteos", "Isquiosurales", "Aductores", "Lumbar", "Core"], ["Barra"]),
    exercise("Peso muerto rumano", "Bisagra de cadera para isquiosurales y gluteos.", "intermediate", "Lleva la cadera atras y conserva la barra pegada a las piernas.", ["Isquiosurales", "Gluteos", "Lumbar", "Espalda"], ["Barra"]),
    exercise("Peso muerto rumano con mancuernas", "Bisagra de cadera con mancuernas para cadena posterior.", "beginner", "Baja hasta sentir tension en isquios sin perder espalda neutra.", ["Isquiosurales", "Gluteos", "Lumbar"], ["Mancuernas"]),
    exercise("Buenos dias con barra", "Bisagra de cadera con barra para cadena posterior.", "advanced", "Usa carga moderada y controla la inclinacion del torso.", ["Isquiosurales", "Gluteos", "Lumbar", "Core"], ["Barra"]),
    exercise("Hiperextensiones lumbares", "Extension de cadera y columna en banco romano.", "beginner", "Sube hasta linea neutra sin hiperextender la espalda.", ["Lumbar", "Gluteos", "Isquiosurales"], ["Banco romano", "Peso corporal"]),

    # Piernas y gluteos
    exercise("Sentadilla con barra", "Sentadilla bilateral con barra para tren inferior.", "intermediate", "Mantener el torso estable y controlar la profundidad segun movilidad.", ["Piernas", "Cuadriceps", "Gluteos", "Core"], ["Barra"], ["Sentadilla"]),
    exercise("Sentadilla frontal", "Sentadilla con barra al frente para enfatizar cuadriceps y torso vertical.", "advanced", "Mantiene codos altos y abdomen firme durante todo el recorrido.", ["Piernas", "Cuadriceps", "Gluteos", "Core"], ["Barra"]),
    exercise("Sentadilla goblet", "Sentadilla con mancuerna o kettlebell sostenida al pecho.", "beginner", "Mantiene el peso cerca del torso y rodillas alineadas.", ["Piernas", "Cuadriceps", "Gluteos", "Core"], ["Mancuernas", "Kettlebell"]),
    exercise("Sentadilla en multipower", "Sentadilla guiada en multipower.", "beginner", "Coloca pies donde puedas bajar sin perder apoyo ni tension.", ["Piernas", "Cuadriceps", "Gluteos"], ["Multipower"]),
    exercise("Sentadilla hack", "Sentadilla guiada en maquina hack para cuadriceps y gluteos.", "beginner", "Apoya la espalda y baja controlando rodillas y profundidad.", ["Piernas", "Cuadriceps", "Gluteos"], ["Hack squat"]),
    exercise("Sentadilla hack inversa", "Variante en hack con torso orientado al respaldo para gluteos y piernas.", "intermediate", "Ajusta pies y cadera para mantener recorrido seguro.", ["Piernas", "Gluteos", "Cuadriceps", "Isquiosurales"], ["Hack squat"]),
    exercise("Sentadilla bulgara", "Sentadilla unilateral con pie trasero elevado.", "intermediate", "Baja vertical y controla la rodilla delantera.", ["Piernas", "Cuadriceps", "Gluteos", "Core"], ["Mancuernas", "Banco"]),
    exercise("Sentadilla bulgara en multipower", "Sentadilla unilateral guiada con pie trasero elevado.", "intermediate", "Ajusta la distancia al banco para evitar molestias de cadera.", ["Piernas", "Cuadriceps", "Gluteos"], ["Multipower", "Banco"]),
    exercise("Sentadilla sumo", "Sentadilla con postura amplia para aductores y gluteos.", "intermediate", "Abre rodillas en linea con los pies y conserva torso firme.", ["Piernas", "Gluteos", "Aductores", "Cuadriceps"], ["Barra"]),
    exercise("Sentadilla con salto", "Sentadilla explosiva con peso corporal.", "intermediate", "Aterriza suave y mantiene rodillas alineadas.", ["Piernas", "Cuadriceps", "Gluteos", "Gemelos"], ["Peso corporal"]),
    exercise("Prensa de piernas", "Empuje de piernas en maquina de prensa.", "beginner", "No bloquees las rodillas y mantiene la pelvis apoyada.", ["Piernas", "Cuadriceps", "Gluteos"], ["Prensa de piernas"]),
    exercise("Prensa de piernas pies altos", "Prensa con pies altos para mayor enfasis en gluteos e isquios.", "beginner", "Mantiene rango controlado sin despegar la cadera del respaldo.", ["Gluteos", "Isquiosurales", "Cuadriceps"], ["Prensa de piernas"]),
    exercise("Prensa de piernas pies bajos", "Prensa con pies bajos para mayor enfasis en cuadriceps.", "beginner", "Controla rodillas y evita acortar el recorrido.", ["Cuadriceps", "Piernas"], ["Prensa de piernas"]),
    exercise("Prensa de piernas unilateral", "Prensa a una pierna para trabajo unilateral.", "intermediate", "Empuja con el pie completo y evita rotar la pelvis.", ["Piernas", "Cuadriceps", "Gluteos"], ["Prensa de piernas"]),
    exercise("Extension de cuadriceps", "Aislamiento de cuadriceps en maquina.", "beginner", "Ajusta el eje de la maquina a la rodilla y controla la bajada.", ["Cuadriceps", "Piernas"], ["Maquina de extension de cuadriceps"]),
    exercise("Extension de cuadriceps unilateral", "Extension de rodilla a una pierna.", "beginner", "Extiende sin impulsos y pausa arriba si no hay molestias.", ["Cuadriceps"], ["Maquina de extension de cuadriceps"]),
    exercise("Zancadas caminando", "Patron unilateral dinamico para piernas y gluteos.", "intermediate", "Da pasos estables y evita que la rodilla colapse hacia dentro.", ["Piernas", "Cuadriceps", "Gluteos", "Core"], ["Mancuernas"]),
    exercise("Zancadas estaticas", "Split squat sin desplazamiento para piernas y gluteos.", "beginner", "Baja vertical y reparte la carga entre ambas piernas.", ["Piernas", "Cuadriceps", "Gluteos"], ["Mancuernas"]),
    exercise("Zancada atras", "Zancada inversa con menor demanda de frenado anterior.", "beginner", "Da el paso atras y mantiene el tronco estable.", ["Piernas", "Cuadriceps", "Gluteos"], ["Mancuernas"]),
    exercise("Zancada lateral", "Desplazamiento lateral para aductores, abductores y gluteos.", "intermediate", "Lleva la cadera atras en la pierna que flexiona.", ["Piernas", "Aductores", "Abductores", "Gluteos"], ["Peso corporal"]),
    exercise("Step up", "Subida a caja o banco para trabajo unilateral de pierna.", "beginner", "Empuja con la pierna apoyada y evita impulsarte con la trasera.", ["Piernas", "Cuadriceps", "Gluteos"], ["Caja pliometrica", "Mancuernas"]),
    exercise("Step up lateral", "Subida lateral a caja para gluteo medio y cuadriceps.", "intermediate", "Controla la bajada y mantiene pelvis estable.", ["Piernas", "Gluteos", "Abductores", "Cuadriceps"], ["Caja pliometrica"]),
    exercise("Hip thrust con barra", "Extension de cadera pesada para gluteos.", "intermediate", "Coloca la pelvis en retroversion arriba y no hiperextiendas lumbar.", ["Gluteos", "Isquiosurales", "Core"], ["Barra", "Banco"]),
    exercise("Hip thrust en maquina", "Extension de cadera guiada para gluteos.", "beginner", "Ajusta el apoyo de cadera y pausa arriba con control.", ["Gluteos", "Isquiosurales"], ["Maquina de gluteos"]),
    exercise("Hip thrust en multipower", "Hip thrust guiado con barra en multipower.", "beginner", "Centra la barra sobre la cadera y evita desplazar el banco.", ["Gluteos", "Isquiosurales"], ["Multipower", "Banco"]),
    exercise("Puente de gluteo", "Extension de cadera desde el suelo para gluteos.", "beginner", "Empuja con talones y bloquea costillas al subir.", ["Gluteos", "Core"], ["Peso corporal"]),
    exercise("Puente de gluteo con barra", "Puente de gluteo cargado desde el suelo.", "intermediate", "Mantiene la barbilla recogida y pausa arriba.", ["Gluteos", "Isquiosurales"], ["Barra"]),
    exercise("Patada de gluteo en polea", "Extension de cadera unilateral en polea.", "beginner", "Evita arquear lumbar y mueve la pierna desde la cadera.", ["Gluteos"], ["Polea baja"]),
    exercise("Patada de gluteo en maquina", "Extension de cadera en maquina especifica de gluteos.", "beginner", "Ajusta el apoyo y empuja sin girar la pelvis.", ["Gluteos"], ["Maquina de gluteos"]),
    exercise("Abductores en maquina", "Abduccion de cadera en maquina para gluteo medio.", "beginner", "Controla la apertura y no uses rebotes.", ["Gluteos", "Abductores"], ["Maquina de abductores"]),
    exercise("Aductores en maquina", "Aduccion de cadera en maquina para aductores.", "beginner", "Cierra con control y evita golpes entre repeticiones.", ["Aductores", "Piernas"], ["Maquina de aductores"]),
    exercise("Abduccion de cadera en polea", "Abduccion unilateral con cable para gluteo medio.", "beginner", "Mantiene torso estable y recorrido controlado.", ["Gluteos", "Abductores"], ["Polea baja"]),
    exercise("Aduccion de cadera en polea", "Aduccion unilateral con cable para aductores.", "beginner", "Cruza la pierna con control sin inclinar el tronco.", ["Aductores"], ["Polea baja"]),
    exercise("Abduccion con banda", "Apertura de cadera con banda elastica.", "beginner", "Mantiene tension constante y rodillas alineadas.", ["Gluteos", "Abductores"], ["Banda elastica"]),
    exercise("Monster walk con banda", "Caminata lateral con banda para gluteo medio.", "beginner", "Da pasos cortos manteniendo tension en la banda.", ["Gluteos", "Abductores"], ["Banda elastica"]),
    exercise("Curl femoral tumbado", "Flexion de rodilla en maquina para isquiosurales.", "beginner", "Ajusta el rodillo y evita levantar la cadera.", ["Isquiosurales", "Piernas"], ["Maquina de curl femoral"]),
    exercise("Curl femoral sentado", "Flexion de rodilla sentado para isquiosurales.", "beginner", "Ajusta el respaldo y controla la extension completa.", ["Isquiosurales", "Piernas"], ["Maquina de curl femoral"]),
    exercise("Curl femoral de pie", "Curl femoral unilateral de pie en maquina.", "beginner", "Flexiona sin mover la cadera y pausa arriba.", ["Isquiosurales"], ["Maquina de curl femoral"]),
    exercise("Curl femoral con fitball", "Flexion de rodilla desde puente con peso corporal.", "intermediate", "Mantiene cadera elevada y controla la extension.", ["Isquiosurales", "Gluteos", "Core"], ["Peso corporal"]),
    exercise("Curl nordico", "Ejercicio excentrico avanzado para isquiosurales.", "advanced", "Desciende lento y usa manos para asistir si es necesario.", ["Isquiosurales", "Gluteos"], ["Peso corporal"]),
    exercise("Peso muerto a una pierna", "Bisagra unilateral para isquios, gluteos y equilibrio.", "intermediate", "Mantiene cadera cuadrada y espalda neutra.", ["Isquiosurales", "Gluteos", "Core"], ["Mancuernas"]),
    exercise("Swing con kettlebell", "Bisagra explosiva de cadera con kettlebell.", "intermediate", "Impulsa con cadera, no con brazos, y mantiene espalda neutra.", ["Gluteos", "Isquiosurales", "Core", "Lumbar"], ["Kettlebell"]),
    exercise("Sentadilla con kettlebell", "Sentadilla goblet usando kettlebell.", "beginner", "Mantiene el peso pegado al pecho y torso firme.", ["Cuadriceps", "Gluteos", "Core"], ["Kettlebell"]),
    exercise("Sentadilla landmine", "Sentadilla con barra anclada en landmine.", "beginner", "Sujeta la barra al pecho y baja con control.", ["Cuadriceps", "Gluteos", "Core"], ["Landmine", "Barra"]),
    exercise("Peso muerto landmine", "Bisagra de cadera con barra en landmine.", "beginner", "Empuja cadera atras y mantiene el extremo de la barra cerca.", ["Gluteos", "Isquiosurales", "Lumbar"], ["Landmine", "Barra"]),
    exercise("Arrastre de trineo hacia atras", "Desplazamiento hacia atras para cuadriceps y acondicionamiento.", "intermediate", "Mantiene pasos cortos y tension continua.", ["Cuadriceps", "Piernas", "Core"], ["Maquina"]),
    exercise("Elevacion de gemelos de pie", "Flexion plantar de pie para gemelos.", "beginner", "Sube completo y baja con control hasta estirar.", ["Gemelos", "Piernas"], ["Maquina de gemelos"]),
    exercise("Elevacion de gemelos sentado", "Trabajo de soleo y gemelos sentado.", "beginner", "Pausa arriba y controla la bajada.", ["Gemelos"], ["Maquina de gemelos"]),
    exercise("Gemelos en prensa", "Elevacion de talones usando prensa de piernas.", "beginner", "No bloquees rodillas y usa recorrido completo de tobillo.", ["Gemelos"], ["Prensa de piernas"]),
    exercise("Gemelos en multipower", "Elevacion de talones con barra guiada.", "beginner", "Coloca puntas sobre una base estable y controla la bajada.", ["Gemelos"], ["Multipower"]),
    exercise("Gemelos con mancuernas", "Elevacion de talones de pie con mancuernas.", "beginner", "Mantiene equilibrio y pausa arriba.", ["Gemelos"], ["Mancuernas"]),
    exercise("Saltos al cajon", "Ejercicio pliometrico para tren inferior.", "intermediate", "Aterriza suave sobre toda la planta y baja con control.", ["Piernas", "Cuadriceps", "Gluteos", "Gemelos"], ["Caja pliometrica", "Peso corporal"]),
    exercise("Burpees", "Ejercicio global de acondicionamiento con flexion y salto.", "intermediate", "Mantiene tecnica consistente y adapta el ritmo a tu capacidad.", ["Piernas", "Pecho", "Hombros", "Core"], ["Peso corporal"]),
    exercise("Wall sit", "Sentadilla isometrica contra pared.", "beginner", "Mantiene rodillas cerca de 90 grados y espalda apoyada.", ["Cuadriceps", "Piernas"], ["Peso corporal"]),
    exercise("Sissy squat", "Sentadilla de alto enfasis en cuadriceps.", "advanced", "Usa rango progresivo y evita dolor de rodilla.", ["Cuadriceps"], ["Peso corporal"]),
    exercise("Cossack squat", "Sentadilla lateral profunda para movilidad y aductores.", "advanced", "Baja controlando tobillo, rodilla y cadera.", ["Piernas", "Aductores", "Gluteos", "Core"], ["Peso corporal"]),
    exercise("Sentadilla hack unilateral", "Sentadilla a una pierna en maquina hack.", "intermediate", "Usa rango controlado y evita que la pelvis rote durante el empuje.", ["Piernas", "Cuadriceps", "Gluteos"], ["Hack squat"]),
    exercise("Peso muerto rumano en multipower", "Bisagra de cadera guiada para isquiosurales y gluteos.", "intermediate", "Coloca pies ligeramente adelantados y conserva la barra cerca.", ["Isquiosurales", "Gluteos", "Lumbar"], ["Multipower"]),
    exercise("Extension de gluteo en banco", "Extension de cadera con apoyo en banco para gluteos.", "beginner", "Aprieta gluteos arriba sin hiperextender la zona lumbar.", ["Gluteos", "Lumbar"], ["Banco", "Peso corporal"]),
    exercise("Gemelos unilateral con mancuerna", "Elevacion de talon a una pierna con mancuerna.", "beginner", "Usa apoyo para equilibrio y completa el recorrido de tobillo.", ["Gemelos"], ["Mancuernas"]),

    # Hombros
    exercise("Press militar con barra", "Empuje vertical para hombros y triceps.", "intermediate", "Bloquear core y evitar hiperextension lumbar.", ["Hombros", "Deltoides", "Triceps", "Core"], ["Barra"], ["Press militar"]),
    exercise("Press militar con mancuernas", "Empuje vertical con mancuernas para hombros.", "intermediate", "Empuja en vertical sin arquear la espalda.", ["Hombros", "Deltoides", "Triceps"], ["Mancuernas"]),
    exercise("Press hombro sentado con mancuernas", "Press vertical sentado para deltoides y triceps.", "beginner", "Apoya la espalda y controla el descenso hasta rango comodo.", ["Hombros", "Deltoides", "Triceps"], ["Mancuernas", "Banco"]),
    exercise("Press hombro en maquina", "Empuje vertical guiado para hombros.", "beginner", "Ajusta el asiento para que las asas empiecen cerca de los hombros.", ["Hombros", "Deltoides", "Triceps"], ["Maquina selectorizada"]),
    exercise("Press hombro en maquina convergente", "Press vertical convergente para deltoides.", "beginner", "Evita encoger los hombros y controla la bajada.", ["Hombros", "Deltoides", "Triceps"], ["Maquina convergente"]),
    exercise("Press hombro en multipower", "Press vertical guiado en multipower.", "beginner", "Coloca el banco centrado y evita bajar tras nuca si molesta.", ["Hombros", "Deltoides", "Triceps"], ["Multipower", "Banco"]),
    exercise("Press Arnold", "Press con rotacion de mancuernas para deltoides.", "intermediate", "Rota con control y evita arquear la espalda.", ["Hombros", "Deltoides", "Triceps"], ["Mancuernas", "Banco"]),
    exercise("Push press", "Press vertical con impulso de piernas para potencia.", "advanced", "Coordina dip y empuje sin perder la linea de la barra.", ["Hombros", "Deltoides", "Triceps", "Piernas", "Core"], ["Barra"]),
    exercise("Elevaciones laterales", "Aislamiento de deltoides lateral con mancuernas.", "beginner", "Eleva hasta la linea de hombros sin balanceo excesivo.", ["Hombros", "Deltoides"], ["Mancuernas"]),
    exercise("Elevaciones laterales en polea", "Deltoides lateral con tension constante en polea.", "beginner", "Mantiene ligera inclinacion y controla el cable.", ["Hombros", "Deltoides"], ["Polea baja"]),
    exercise("Elevaciones laterales en maquina", "Aislamiento guiado del deltoides lateral.", "beginner", "Ajusta el eje de la maquina y evita subir trapecios.", ["Hombros", "Deltoides"], ["Maquina selectorizada"]),
    exercise("Elevaciones laterales sentado", "Elevacion lateral estricta con menor impulso.", "beginner", "Sienta el torso estable y usa carga moderada.", ["Hombros", "Deltoides"], ["Mancuernas", "Banco"]),
    exercise("Elevacion lateral unilateral", "Elevacion lateral a un brazo para controlar asimetrias.", "beginner", "Mantiene el hombro abajo y recorrido limpio.", ["Hombros", "Deltoides"], ["Mancuernas"]),
    exercise("Elevaciones frontales con mancuernas", "Aislamiento de deltoides anterior.", "beginner", "Eleva hasta hombros sin balanceo ni extension lumbar.", ["Hombros", "Deltoides"], ["Mancuernas"]),
    exercise("Elevaciones frontales con disco", "Elevacion frontal sujetando un disco.", "beginner", "Mantiene brazos ligeramente flexionados y tronco estable.", ["Hombros", "Deltoides"], ["Disco"]),
    exercise("Elevacion frontal en polea", "Deltoides anterior con polea baja.", "beginner", "Controla la bajada y evita tirar con la espalda.", ["Hombros", "Deltoides"], ["Polea baja"]),
    exercise("Pajaros en polea", "Deltoides posterior en cruce de poleas.", "beginner", "Cruza cables y abre con codos suaves sin encoger hombros.", ["Hombros", "Deltoides", "Trapecio"], ["Cruce de poleas"]),
    exercise("Remo al menton con barra", "Tiron vertical para deltoides lateral y trapecio.", "intermediate", "Sube hasta rango comodo sin dolor de hombro.", ["Hombros", "Deltoides", "Trapecio"], ["Barra"]),
    exercise("Remo al menton en polea", "Tiron vertical con cable para hombro y trapecio.", "intermediate", "Mantiene codos altos solo si el hombro lo tolera.", ["Hombros", "Deltoides", "Trapecio"], ["Polea baja"]),
    exercise("Y raise en banco inclinado", "Elevacion en Y para deltoides, trapecio bajo y control escapular.", "beginner", "Usa carga ligera y evita encoger el cuello.", ["Hombros", "Deltoides", "Trapecio", "Espalda"], ["Mancuernas", "Banco"]),
    exercise("Rotacion externa en polea", "Trabajo de rotadores externos del hombro.", "beginner", "Mantiene codo fijo y usa carga baja.", ["Hombros", "Deltoides"], ["Polea baja"]),
    exercise("Rotacion externa con banda", "Rotadores externos con resistencia elastica.", "beginner", "Mantiene codo pegado al cuerpo y movimiento controlado.", ["Hombros", "Deltoides"], ["Banda elastica"]),
    exercise("Press landmine unilateral", "Empuje diagonal con landmine para hombro y core.", "beginner", "Empuja en diagonal y evita rotar el tronco.", ["Hombros", "Deltoides", "Triceps", "Core"], ["Landmine", "Barra"]),
    exercise("Press landmine bilateral", "Empuje diagonal con ambas manos en landmine.", "beginner", "Mantiene costillas bajas y codos bajo control.", ["Hombros", "Pecho", "Triceps", "Core"], ["Landmine", "Barra"]),
    exercise("Handstand push up", "Flexion vertical invertida con peso corporal.", "advanced", "Progresar con seguridad y controlar cuello y hombros.", ["Hombros", "Deltoides", "Triceps", "Core"], ["Peso corporal"]),
    exercise("Press pecho unilateral en maquina", "Empuje horizontal a un brazo en maquina para controlar asimetrias.", "beginner", "Mantiene el torso pegado al respaldo y evita rotar al empujar.", ["Pecho", "Hombros", "Triceps", "Core"], ["Maquina convergente"]),
    exercise("Remo unilateral en maquina", "Remo a un brazo en maquina para dorsales y espalda media.", "beginner", "Tira con el codo hacia atras sin girar el tronco.", ["Espalda", "Dorsales", "Biceps"], ["Maquina convergente"]),

    # Brazos
    exercise("Curl biceps con barra", "Flexion de codo con barra para biceps.", "beginner", "Evita balanceo y controla la fase excentrica.", ["Brazos", "Biceps"], ["Barra"], ["Curl biceps"]),
    exercise("Curl biceps con barra Z", "Curl con barra Z para reducir tension en munecas.", "beginner", "Mantiene codos cerca del torso y evita impulso.", ["Brazos", "Biceps", "Antebrazos"], ["Barra"]),
    exercise("Curl biceps con mancuernas", "Curl alterno o simultaneo con mancuernas.", "beginner", "Supina al subir y baja con control.", ["Brazos", "Biceps"], ["Mancuernas"]),
    exercise("Curl alterno con mancuernas", "Curl alternando brazos para controlar la tecnica.", "beginner", "Evita inclinar el tronco y completa cada repeticion.", ["Brazos", "Biceps"], ["Mancuernas"]),
    exercise("Curl martillo", "Curl con agarre neutro para braquial y antebrazo.", "beginner", "Mantiene pulgares hacia arriba y codos estables.", ["Brazos", "Biceps", "Antebrazos"], ["Mancuernas"]),
    exercise("Curl inclinado con mancuernas", "Curl en banco inclinado con gran estiramiento del biceps.", "intermediate", "No adelantes los codos y controla la bajada.", ["Brazos", "Biceps"], ["Mancuernas", "Banco"]),
    exercise("Curl concentrado", "Curl unilateral sentado con apoyo en el muslo.", "beginner", "Sube sin balancear el hombro y aprieta arriba.", ["Brazos", "Biceps"], ["Mancuernas", "Banco"]),
    exercise("Curl predicador", "Curl en banco Scott para aislar biceps.", "beginner", "Apoya bien los brazos y no hiperextiendas el codo abajo.", ["Brazos", "Biceps"], ["Banco Scott", "Barra"]),
    exercise("Curl predicador con mancuerna", "Curl unilateral en banco Scott.", "beginner", "Controla el rango bajo y evita rotar el torso.", ["Brazos", "Biceps"], ["Banco Scott", "Mancuernas"]),
    exercise("Curl predicador en maquina", "Curl guiado en maquina de banco Scott.", "beginner", "Ajusta asiento y eje para no forzar codos.", ["Brazos", "Biceps"], ["Maquina selectorizada", "Banco Scott"]),
    exercise("Curl en polea baja", "Curl con cable para tension constante.", "beginner", "Mantiene codos fijos y controla el retorno.", ["Brazos", "Biceps"], ["Polea baja"]),
    exercise("Curl en polea alta", "Curl doble desde poleas altas para biceps.", "intermediate", "Mantiene brazos elevados y flexiona sin mover hombros.", ["Brazos", "Biceps"], ["Cruce de poleas", "Polea alta"]),
    exercise("Curl spider", "Curl con pecho apoyado en banco inclinado.", "intermediate", "Deja brazos colgando y flexiona sin balanceo.", ["Brazos", "Biceps"], ["Mancuernas", "Banco"]),
    exercise("Curl 21", "Serie combinada de rangos parciales y completos para biceps.", "intermediate", "Mantiene carga moderada y tecnica estricta.", ["Brazos", "Biceps"], ["Barra"]),
    exercise("Curl inverso con barra", "Curl pronado para braquial y antebrazos.", "intermediate", "Usa agarre pronado y evita doblar munecas.", ["Brazos", "Biceps", "Antebrazos"], ["Barra"]),
    exercise("Curl martillo en cuerda", "Curl en polea con cuerda y agarre neutro.", "beginner", "Separa la cuerda arriba sin mover codos.", ["Brazos", "Biceps", "Antebrazos"], ["Polea baja"]),
    exercise("Extension triceps con cuerda", "Extension de codo en polea con cuerda.", "beginner", "Mantener codos estables y extender completamente.", ["Brazos", "Triceps"], ["Polea alta"], ["Extension triceps en polea"]),
    exercise("Extension triceps con barra", "Extension de codo en polea con barra recta.", "beginner", "Pega codos al torso y evita inclinarte demasiado.", ["Brazos", "Triceps"], ["Polea alta"]),
    exercise("Extension triceps agarre inverso", "Extension en polea con agarre supino.", "beginner", "Usa carga controlada y mantiene munecas firmes.", ["Brazos", "Triceps", "Antebrazos"], ["Polea alta"]),
    exercise("Extension triceps unilateral en polea", "Extension de codo a un brazo en polea.", "beginner", "Mantiene hombro quieto y completa el recorrido.", ["Brazos", "Triceps"], ["Polea alta"]),
    exercise("Extension triceps por encima de la cabeza en polea", "Extension sobre la cabeza para cabeza larga del triceps.", "intermediate", "Mantiene codos altos y abdomen firme.", ["Brazos", "Triceps"], ["Polea alta"]),
    exercise("Extension triceps con mancuerna a dos manos", "Extension sobre la cabeza con una mancuerna.", "beginner", "No abras demasiado los codos y controla la bajada.", ["Brazos", "Triceps"], ["Mancuernas"]),
    exercise("Extension triceps unilateral con mancuerna", "Extension sobre la cabeza a un brazo.", "intermediate", "Mantiene codo apuntando arriba y rango sin dolor.", ["Brazos", "Triceps"], ["Mancuernas"]),
    exercise("Press frances con barra", "Extension de triceps tumbado con barra.", "intermediate", "Mantiene codos apuntando arriba y baja controlado.", ["Brazos", "Triceps"], ["Barra", "Banco"]),
    exercise("Press frances con mancuernas", "Extension tumbada de triceps con mancuernas.", "intermediate", "Controla el recorrido y evita abrir los codos.", ["Brazos", "Triceps"], ["Mancuernas", "Banco"]),
    exercise("Rompecraneos", "Extension de triceps tumbado hacia la frente.", "intermediate", "Usa carga controlada y no rebotes al final del recorrido.", ["Brazos", "Triceps"], ["Barra", "Banco"]),
    exercise("Fondos en paralelas", "Empuje en paralelas con enfasis en triceps.", "intermediate", "Mantiene torso mas vertical para cargar triceps.", ["Brazos", "Triceps", "Pecho", "Hombros"], ["Paralelas", "Peso corporal"]),
    exercise("Fondos entre bancos", "Fondo de triceps usando banco.", "beginner", "Baja con control y no fuerces el hombro en profundidad.", ["Brazos", "Triceps", "Hombros"], ["Banco", "Peso corporal"]),
    exercise("Patada de triceps", "Extension de codo con mancuerna desde bisagra.", "beginner", "Mantiene brazo pegado al cuerpo y extiende sin balanceo.", ["Brazos", "Triceps"], ["Mancuernas"]),
    exercise("Patada de triceps en polea", "Extension posterior de codo con cable.", "beginner", "Mantiene hombro fijo y controla el retorno.", ["Brazos", "Triceps"], ["Polea baja"]),
    exercise("Press cerrado en multipower", "Press de agarre cerrado guiado para triceps.", "intermediate", "Baja con codos controlados y munecas neutras.", ["Brazos", "Triceps", "Pecho"], ["Multipower", "Banco"]),
    exercise("Extension triceps en maquina", "Extension de codo guiada en maquina.", "beginner", "Ajusta asiento y apoya brazos antes de empujar.", ["Brazos", "Triceps"], ["Maquina selectorizada"]),
    exercise("Curl de muneca con barra", "Flexion de muneca para antebrazos.", "beginner", "Usa rango controlado y carga ligera.", ["Antebrazos", "Brazos"], ["Barra", "Banco"]),
    exercise("Curl inverso de muneca", "Extension de muneca para antebrazos.", "beginner", "Apoya antebrazos y mueve solo las munecas.", ["Antebrazos"], ["Barra", "Banco"]),
    exercise("Farmer walk", "Caminata cargada para agarre, trapecio y core.", "intermediate", "Camina erguido con hombros estables y abdomen firme.", ["Antebrazos", "Trapecio", "Core", "Piernas"], ["Mancuernas", "Kettlebell"]),
    exercise("Dead hang", "Colgado pasivo o activo para agarre y hombros.", "beginner", "Mantiene agarre firme y controla la posicion escapular.", ["Antebrazos", "Espalda", "Hombros"], ["Barra de dominadas", "Peso corporal"]),
    exercise("Pinza con discos", "Agarre de pinza sosteniendo discos.", "intermediate", "Mantiene discos juntos y postura estable.", ["Antebrazos"], ["Disco"]),
    exercise("Curl femoral unilateral sentado", "Curl femoral sentado a una pierna para corregir asimetrias.", "beginner", "Controla la fase de vuelta y no levantes la cadera del asiento.", ["Isquiosurales"], ["Maquina de curl femoral"]),
    exercise("Crunch oblicuo en polea", "Flexion lateral y rotacional ligera en polea para oblicuos.", "beginner", "Usa carga moderada y evita tirar con brazos o cuello.", ["Core", "Oblicuos"], ["Polea alta"]),

    # Core
    exercise("Plancha", "Ejercicio isometrico de core.", "beginner", "Mantener linea recta de cabeza a pies sin hundir la cadera.", ["Core"], ["Peso corporal"], ["Plancha"]),
    exercise("Plancha lateral", "Isometrico lateral para oblicuos y estabilidad de cadera.", "beginner", "Mantiene cadera alta y cuerpo alineado.", ["Core", "Oblicuos", "Gluteos"], ["Peso corporal"]),
    exercise("Plancha con toque de hombros", "Plancha dinamica alternando toques de hombro.", "intermediate", "Evita rotar la pelvis al levantar cada mano.", ["Core", "Hombros"], ["Peso corporal"]),
    exercise("Plancha con desplazamiento", "Plancha dinamica caminando con manos o pies.", "intermediate", "Mantiene abdomen firme y pasos cortos.", ["Core", "Hombros", "Pecho"], ["Peso corporal"]),
    exercise("Crunch abdominal", "Flexion controlada de tronco para abdomen.", "beginner", "Eleva escapulas sin tirar del cuello.", ["Core"], ["Peso corporal"]),
    exercise("Crunch en maquina", "Flexion de tronco guiada en maquina abdominal.", "beginner", "Ajusta el asiento y flexiona desde el abdomen.", ["Core"], ["Maquina selectorizada"]),
    exercise("Crunch en polea", "Flexion de tronco con cable para abdomen.", "beginner", "Redondea el tronco llevando costillas hacia pelvis.", ["Core"], ["Polea alta"]),
    exercise("Crunch inverso", "Elevacion de pelvis para abdomen inferior.", "beginner", "Eleva la pelvis sin impulsarte con las piernas.", ["Core"], ["Peso corporal"]),
    exercise("Elevaciones de piernas", "Elevacion de piernas tumbado para abdomen y flexores de cadera.", "beginner", "Mantiene lumbar controlada y baja sin arquear.", ["Core"], ["Peso corporal"]),
    exercise("Elevaciones de piernas colgado", "Elevacion de piernas desde barra para core avanzado.", "advanced", "Evita balanceo y sube con control.", ["Core", "Antebrazos"], ["Barra de dominadas", "Peso corporal"]),
    exercise("Elevaciones de rodillas colgado", "Elevacion de rodillas en barra para abdomen.", "intermediate", "Controla el balanceo y lleva rodillas hacia el pecho.", ["Core", "Antebrazos"], ["Barra de dominadas", "Peso corporal"]),
    exercise("Elevaciones de rodillas en paralelas", "Elevacion de rodillas con apoyo en paralelas.", "beginner", "Apoya antebrazos y sube rodillas sin impulso.", ["Core"], ["Paralelas", "Peso corporal"]),
    exercise("Rueda abdominal", "Extension anti-extension con rueda abdominal.", "advanced", "Avanza solo hasta donde puedas volver sin hundir lumbar.", ["Core", "Hombros"], ["Peso corporal"]),
    exercise("Dead bug", "Control lumbopelvico alternando brazos y piernas.", "beginner", "Mantiene lumbar estable contra el suelo.", ["Core"], ["Peso corporal"]),
    exercise("Bird dog", "Estabilidad de core extendiendo brazo y pierna opuestos.", "beginner", "Evita rotar la pelvis y pausa al extender.", ["Core", "Lumbar", "Gluteos"], ["Peso corporal"]),
    exercise("Mountain climbers", "Trabajo dinamico de core y acondicionamiento.", "beginner", "Mantiene hombros sobre manos y cadera estable.", ["Core", "Hombros", "Piernas"], ["Peso corporal"]),
    exercise("Russian twist", "Rotacion de tronco para oblicuos.", "beginner", "Gira desde el torso y no solo con los brazos.", ["Core", "Oblicuos"], ["Peso corporal", "Disco"]),
    exercise("Giros con balon medicinal", "Rotaciones de tronco con balon medicinal.", "intermediate", "Mantiene cadera estable y rota con control.", ["Core", "Oblicuos"], ["Balon medicinal"]),
    exercise("Lanzamiento rotacional con balon medicinal", "Trabajo explosivo de rotacion para core.", "advanced", "Rota cadera y torso coordinadamente sin perder control.", ["Core", "Oblicuos", "Piernas"], ["Balon medicinal"]),
    exercise("Pallof press", "Anti-rotacion con polea o banda.", "beginner", "Empuja al frente sin dejar que el tronco rote.", ["Core", "Oblicuos"], ["Polea", "Banda elastica"]),
    exercise("Pallof press en polea", "Anti-rotacion usando cable a la altura del pecho.", "beginner", "Mantiene pies firmes y brazos alineados al centro.", ["Core", "Oblicuos"], ["Polea baja"]),
    exercise("Woodchopper en polea", "Rotacion diagonal de tronco con cable.", "intermediate", "Gira con torso y cadera sin tirar solo de brazos.", ["Core", "Oblicuos"], ["Polea alta"]),
    exercise("Woodchopper con banda", "Rotacion diagonal con banda elastica.", "beginner", "Mantiene tension constante y controla el regreso.", ["Core", "Oblicuos"], ["Banda elastica"]),
    exercise("Sit up", "Flexion completa de tronco desde el suelo.", "beginner", "Sube controlado y evita tirar del cuello.", ["Core"], ["Peso corporal"]),
    exercise("V ups", "Flexion simultanea de tronco y piernas.", "intermediate", "Coordina subida sin perder control lumbar.", ["Core"], ["Peso corporal"]),
    exercise("Hollow hold", "Isometrico anti-extension en posicion hollow.", "intermediate", "Mantiene lumbar pegada al suelo y ajusta palancas.", ["Core"], ["Peso corporal"]),
    exercise("Superman", "Extension de espalda y cadera desde prono.", "beginner", "Eleva brazos y piernas sin forzar cervicales.", ["Lumbar", "Gluteos", "Espalda"], ["Peso corporal"]),
    exercise("Buenos dias con banda", "Bisagra de cadera con banda para lumbar y gluteos.", "beginner", "Controla la cadera atras y vuelve apretando gluteos.", ["Lumbar", "Gluteos", "Isquiosurales"], ["Banda elastica"]),
    exercise("Carry unilateral", "Caminata con carga a un lado para anti-inclinacion.", "intermediate", "Camina erguido sin inclinarte hacia la carga.", ["Core", "Oblicuos", "Antebrazos"], ["Mancuernas", "Kettlebell"]),
    exercise("Turkish get up", "Levantamiento complejo con kettlebell para core y hombro.", "advanced", "Avanza paso a paso con carga ligera y mirada estable.", ["Core", "Hombros", "Gluteos", "Piernas"], ["Kettlebell"]),
]

RANKS = [
    {
        "name": "Novato",
        "description": "Rango inicial hasta registrar rendimiento con carga suficiente.",
        "min_score": "0",
        "sort_order": 1,
    },
    {
        "name": "Principiante",
        "description": "Primer progreso medible por volumen o mejora de carga.",
        "min_score": "100",
        "sort_order": 2,
    },
    {
        "name": "Intermedio",
        "description": "Rendimiento consistente con volumen y progresion acumulada.",
        "min_score": "300",
        "sort_order": 3,
    },
    {
        "name": "Avanzado",
        "description": "Buenas marcas y progreso en varios ejercicios.",
        "min_score": "700",
        "sort_order": 4,
    },
    {
        "name": "Atleta",
        "description": "Alto rendimiento acumulado por carga y progresion.",
        "min_score": "1500",
        "sort_order": 5,
    },
    {
        "name": "Elite",
        "description": "Rendimiento muy alto sostenido en multiples levantamientos.",
        "min_score": "3000",
        "sort_order": 6,
    },
    {
        "name": "Leyenda",
        "description": "Nivel maximo del sistema inicial de rangos.",
        "min_score": "6000",
        "sort_order": 7,
    },
]
